### PR TITLE
v0.4.0 - try 3

### PR DESCRIPTION
**Pull request by ashwinvis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #4 #5

### CODE REVIEW

**Comment by ashwinvis** [comment]
@conda-forge-admin, please rerender

**Comment by paugier** [comment]
It strange that no build was triggered!

**Comment by ashwinvis** [comment]
@conda-forge-admin, please restart ci

**Comment by paugier** [comment]
I guess we need a new build of fluidfft...

**Comment by ashwinvis** [comment]
Same "Illegal instruction ... core dump" on linux

**Comment by paugier** [comment]
I'm going to open a PR for a new build of fluidfft.

**Comment by ashwinvis** [comment]
@conda-forge-admin, please restart ci

**Comment by ashwinvis** [comment]
@paugier Good to go.

**Comment by ashwinvis** [comment]
Ping @paugier

**Pull request merged**
