### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by ashwinvis**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Obsoletes #4

### CODE REVIEW

**Comment by ashwinvis** [comment]
@conda-forge-admin, please rerender

**Comment by ashwinvis** [comment]
For linux, failed at `fluidsim-test -v` during `test_curl` and core dumped. Not sure why.

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=266000&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=2132

For osx. something to do with mpi during `test_bench`:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=266000&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=f047df50-a233-5ae9-bf8f-c7dd8e5684ad&l=2778

**Comment by paugier** [comment]
> For linux, failed at fluidsim-test -v during test_curl and core dumped. Not sure why.

"Illegal instruction"

It means that something has been built in conda with `arch=native` (or something like that).

**Comment by paugier** [comment]
> For osx. something to do with mpi during test_bench:

The second one is something really simple (just a fluidsim bug when cpu_count is 1). I don't think it has anything to do with MPI.

**Comment by paugier** [comment]
Next release it should work on OSX: https://foss.heptapod.net/fluiddyn/fluidsim/-/merge_requests/193

**Comment by paugier** [comment]
For the first problem (Illegal instruction), in fluidsim (https://foss.heptapod.net/fluiddyn/fluidsim/-/blob/branch/default/setup.py#L139) and fluidfft (https://foss.heptapod.net/fluiddyn/fluidfft/-/blob/branch/default/setup_make.py#L501), we build with `-march=native` by default.

I guess the simpler solution would be to set `CARCH` to something more reasonable for package builds (conda and wheels, but we don't upload wheels so only conda). I don't know what would be a reasonable value for `CARCH` on conda. We need to be compatible with simple CPU.

**Comment by paugier** [comment]
We should try with `CARCH=x86-64`.

**Comment by paugier** [comment]
Since we have problem on all platforms and we won't be able to run fluidsim 0.4.0 tests on OSX, I think we can disable builds on Windows for this version.

For OSX, we can just disable the tests! Just check that `import fluidsim` works.

Once fluidfft will be built without march=native on conda, we should be able to at least build the packages for Linux in this PR.

**Comment by ashwinvis** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
